### ISSUE TITLE
Remove `as any` deferred initialization of `ctx.wrap` in `defineMacro`

### ISSUE THREAD

**Issue by rohal12** [rohal12/spindle#72]
## Problem

In `src/define-macro.ts`, the `ctx` object is constructed with `wrap: undefined as any` (line 133) because the real `wrap` function (assigned at line 152) closes over `ctx.className` and `ctx.id`, which may be modified by the `config.merged` and `config.storeVar` branches before `wrap` is assigned.

```ts
// line 116–134: ctx is created with a placeholder
const ctx: MacroContext = {
  // ... other properties ...
  cls: macroClass(config.name, className),
  mutate: (code: string) => executeMutation(code, getValues(), update),
  update,
  getValues,
  wrap: undefined as any,   // <-- type safety hole
};

// lines 136–150: conditional mutations to ctx (merged, storeVar)
if (config.merged) { /* ... */ }
if (config.storeVar) { /* ... */ }

// line 152–156: wrap is finally assigned its real implementation
ctx.wrap = (content: ComponentChildren): VNode<any> => {
  if (ctx.className || ctx.id)
    return h('span', { id: ctx.id, class: ctx.className }, content);
  return h(Fragment, null, content);
};

// line 158: ctx is passed to the macro's render function
return config.render(props, ctx);
```

Between lines 133 and 152, `ctx.wrap` is `undefined` even though `MacroContext.wrap` is typed as `(content: ComponentChildren) => VNode<any>` (non-optional). The `as any` cast silences TypeScript entirely.

## Why it exists

The `wrap` function reads `ctx.className` and `ctx.id` at call time (via closure over `ctx`). Since `className`/`id` may be set during the `config.interpolate` step (lines 102–106) and the `ctx` object literal needs all properties present at construction, the author deferred `wrap`'s real assignment until after all conditional setup is complete.

## Impact

**Low practical risk** — `config.render(props, ctx)` is the only consumer of `ctx`, and it is called on line 158, well after `wrap` is assigned on line 152. No macro can observe the `undefined` gap at runtime today.

However, the `as any` cast is still problematic:

1. **Masks potential bugs:** If someone copies this pattern or adds code between lines 134–151 that calls `ctx.wrap(...)`, TypeScript will not catch the runtime error.
2. **Violates type safety:** The `MacroContext` interface declares `wrap` as non-optional, but `as any` makes that guarantee meaningless during construction.
3. **Code smell:** `as any` in core infrastructure code sets a bad precedent and makes it harder to enforce strict typing elsewhere in the codebase.

## Suggested fix

**Option A — Initialize with a no-op / throw function:**

Replace the `undefined as any` with a safe sentinel that satisfies the type and fails loudly if called prematurely:

```ts
const ctx: MacroContext = {
  // ...
  wrap: () => { throw new Error('ctx.wrap called before initialization'); },
};
```

This eliminates the `as any` entirely. TypeScript is satisfied, and any accidental early call produces a clear error instead of a cryptic "undefined is not a function."

**Option B — Restructure to avoid deferred assignment:**

Since `wrap` only reads `ctx.className` and `ctx.id` (which are already available at ctx construction time and are not reassigned afterwards), the `wrap` closure could be defined inline in the object literal:

```ts
const ctx: MacroContext = {
  // ...
  className,
  id,
  wrap: (content: ComponentChildren): VNode<any> => {
    if (className || id)
      return h('span', { id, class: className }, content);
    return h(Fragment, null, content);
  },
};
```

This works because `className` and `id` are `let` bindings resolved before `ctx` is constructed (lines 99–106), and they are never reassigned after that point. This approach removes both the `as any` and the deferred mutation of `ctx.wrap`.

Option B is the cleanest solution since it eliminates the deferred initialization pattern entirely.
